# Generated by protoc_gen_nim. Do not edit!

import intsets

import protobuf/gen
import protobuf/stream
import protobuf/types

import phonenumber_pb

const
    PersonDesc = MessageDesc(
        name: "Person",
        fields: @[
            FieldDesc(
                name: "name",
                number: 1,
                ftype: FieldType.String,
                label: FieldLabel.Optional,
                typeName: "",
                packed: false,
            ),
            FieldDesc(
                name: "id",
                number: 2,
                ftype: FieldType.Int32,
                label: FieldLabel.Optional,
                typeName: "",
                packed: false,
            ),
            FieldDesc(
                name: "email",
                number: 3,
                ftype: FieldType.String,
                label: FieldLabel.Optional,
                typeName: "",
                packed: false,
            ),
            FieldDesc(
                name: "phones",
                number: 4,
                ftype: FieldType.Message,
                label: FieldLabel.Repeated,
                typeName: "PhoneNumber",
                packed: false,
            ),
        ]
    )
    AddressBookDesc = MessageDesc(
        name: "AddressBook",
        fields: @[
            FieldDesc(
                name: "people",
                number: 1,
                ftype: FieldType.Message,
                label: FieldLabel.Repeated,
                typeName: "Person",
                packed: false,
            ),
        ]
    )
generateMessageType(PersonDesc)
generateMessageProcs(PersonDesc)
generateMessageType(AddressBookDesc)
generateMessageProcs(AddressBookDesc)
