# Generated by protoc_gen_nim. Do not edit!

import intsets

import protobuf/gen
import protobuf/stream
import protobuf/types

const
    PhoneTypeDesc = EnumDesc(
        name: "PhoneType",
        values: @[
            EnumValueDesc(name: "MOBILE", number: 0),
            EnumValueDesc(name: "HOME", number: 1),
            EnumValueDesc(name: "WORK", number: 2),
        ]
    )
    PhoneNumberDesc = MessageDesc(
        name: "PhoneNumber",
        fields: @[
            FieldDesc(
                name: "number",
                number: 1,
                ftype: FieldType.String,
                label: FieldLabel.Optional,
                typeName: "",
                packed: false,
            ),
            FieldDesc(
                name: "type",
                number: 2,
                ftype: FieldType.Enum,
                label: FieldLabel.Optional,
                typeName: "PhoneType",
                packed: false,
            ),
        ]
    )
generateEnumType(PhoneTypeDesc)
generateEnumProcs(PhoneTypeDesc)
generateMessageType(PhoneNumberDesc)
generateMessageProcs(PhoneNumberDesc)
