# Generated by protoc_gen_nim. Do not edit!

import base64
import intsets
import json
import strutils

import nimpb/nimpb
import nimpb/json as nimpb_json

import nimpb/wkt/source_context_pb
import nimpb/wkt/type_pb

type
    google_protobuf_Api* = ref google_protobuf_ApiObj
    google_protobuf_ApiObj* = object of Message
        name: string
        methods: seq[google_protobuf_Method]
        options: seq[google_protobuf_Option]
        version: string
        sourceContext: google_protobuf_SourceContext
        mixins: seq[google_protobuf_Mixin]
        syntax: google_protobuf_Syntax
    google_protobuf_Method* = ref google_protobuf_MethodObj
    google_protobuf_MethodObj* = object of Message
        name: string
        requestTypeUrl: string
        requestStreaming: bool
        responseTypeUrl: string
        responseStreaming: bool
        options: seq[google_protobuf_Option]
        syntax: google_protobuf_Syntax
    google_protobuf_Mixin* = ref google_protobuf_MixinObj
    google_protobuf_MixinObj* = object of Message
        name: string
        root: string

proc newgoogle_protobuf_Method*(): google_protobuf_Method
proc newgoogle_protobuf_Method*(data: string): google_protobuf_Method
proc newgoogle_protobuf_Method*(data: seq[byte]): google_protobuf_Method
proc writegoogle_protobuf_Method*(stream: Stream, message: google_protobuf_Method)
proc readgoogle_protobuf_Method*(stream: Stream): google_protobuf_Method
proc sizeOfgoogle_protobuf_Method*(message: google_protobuf_Method): uint64
proc toJson*(message: google_protobuf_Method): JsonNode
proc parsegoogle_protobuf_Method*(obj: JsonNode): google_protobuf_Method

proc newgoogle_protobuf_Mixin*(): google_protobuf_Mixin
proc newgoogle_protobuf_Mixin*(data: string): google_protobuf_Mixin
proc newgoogle_protobuf_Mixin*(data: seq[byte]): google_protobuf_Mixin
proc writegoogle_protobuf_Mixin*(stream: Stream, message: google_protobuf_Mixin)
proc readgoogle_protobuf_Mixin*(stream: Stream): google_protobuf_Mixin
proc sizeOfgoogle_protobuf_Mixin*(message: google_protobuf_Mixin): uint64
proc toJson*(message: google_protobuf_Mixin): JsonNode
proc parsegoogle_protobuf_Mixin*(obj: JsonNode): google_protobuf_Mixin

proc newgoogle_protobuf_Api*(): google_protobuf_Api
proc newgoogle_protobuf_Api*(data: string): google_protobuf_Api
proc newgoogle_protobuf_Api*(data: seq[byte]): google_protobuf_Api
proc writegoogle_protobuf_Api*(stream: Stream, message: google_protobuf_Api)
proc readgoogle_protobuf_Api*(stream: Stream): google_protobuf_Api
proc sizeOfgoogle_protobuf_Api*(message: google_protobuf_Api): uint64
proc toJson*(message: google_protobuf_Api): JsonNode
proc parsegoogle_protobuf_Api*(obj: JsonNode): google_protobuf_Api

proc fullyQualifiedName*(T: typedesc[google_protobuf_Method]): string = "google.protobuf.Method"

proc readgoogle_protobuf_MethodImpl(stream: Stream): Message = readgoogle_protobuf_Method(stream)
proc writegoogle_protobuf_MethodImpl(stream: Stream, msg: Message) = writegoogle_protobuf_Method(stream, google_protobuf_Method(msg))
proc toJsongoogle_protobuf_MethodImpl(msg: Message): JsonNode = toJson(google_protobuf_Method(msg))
proc fromJsongoogle_protobuf_MethodImpl(node: JsonNode): Message = parsegoogle_protobuf_Method(node)

proc google_protobuf_MethodProcs*(): MessageProcs =
    result.readImpl = readgoogle_protobuf_MethodImpl
    result.writeImpl = writegoogle_protobuf_MethodImpl
    result.toJsonImpl = toJsongoogle_protobuf_MethodImpl
    result.fromJsonImpl = fromJsongoogle_protobuf_MethodImpl

proc newgoogle_protobuf_Method*(): google_protobuf_Method =
    new(result)
    initMessage(result[])
    result.procs = google_protobuf_MethodProcs()
    result.name = ""
    result.requestTypeUrl = ""
    result.requestStreaming = false
    result.responseTypeUrl = ""
    result.responseStreaming = false
    result.options = @[]
    result.syntax = google_protobuf_Syntax.SYNTAX_PROTO2

proc clearname*(message: google_protobuf_Method) =
    message.name = ""

proc setname*(message: google_protobuf_Method, value: string) =
    message.name = value

proc name*(message: google_protobuf_Method): string {.inline.} =
    message.name

proc `name=`*(message: google_protobuf_Method, value: string) {.inline.} =
    setname(message, value)

proc clearrequestTypeUrl*(message: google_protobuf_Method) =
    message.requestTypeUrl = ""

proc setrequestTypeUrl*(message: google_protobuf_Method, value: string) =
    message.requestTypeUrl = value

proc requestTypeUrl*(message: google_protobuf_Method): string {.inline.} =
    message.requestTypeUrl

proc `requestTypeUrl=`*(message: google_protobuf_Method, value: string) {.inline.} =
    setrequestTypeUrl(message, value)

proc clearrequestStreaming*(message: google_protobuf_Method) =
    message.requestStreaming = false

proc setrequestStreaming*(message: google_protobuf_Method, value: bool) =
    message.requestStreaming = value

proc requestStreaming*(message: google_protobuf_Method): bool {.inline.} =
    message.requestStreaming

proc `requestStreaming=`*(message: google_protobuf_Method, value: bool) {.inline.} =
    setrequestStreaming(message, value)

proc clearresponseTypeUrl*(message: google_protobuf_Method) =
    message.responseTypeUrl = ""

proc setresponseTypeUrl*(message: google_protobuf_Method, value: string) =
    message.responseTypeUrl = value

proc responseTypeUrl*(message: google_protobuf_Method): string {.inline.} =
    message.responseTypeUrl

proc `responseTypeUrl=`*(message: google_protobuf_Method, value: string) {.inline.} =
    setresponseTypeUrl(message, value)

proc clearresponseStreaming*(message: google_protobuf_Method) =
    message.responseStreaming = false

proc setresponseStreaming*(message: google_protobuf_Method, value: bool) =
    message.responseStreaming = value

proc responseStreaming*(message: google_protobuf_Method): bool {.inline.} =
    message.responseStreaming

proc `responseStreaming=`*(message: google_protobuf_Method, value: bool) {.inline.} =
    setresponseStreaming(message, value)

proc clearoptions*(message: google_protobuf_Method) =
    message.options = @[]
    clearFields(message, [6])

proc hasoptions*(message: google_protobuf_Method): bool =
    result = hasField(message, 6) or (len(message.options) > 0)

proc setoptions*(message: google_protobuf_Method, value: seq[google_protobuf_Option]) =
    message.options = value
    setField(message, 6)

proc addoptions*(message: google_protobuf_Method, value: google_protobuf_Option) =
    add(message.options, value)

proc options*(message: google_protobuf_Method): seq[google_protobuf_Option] {.inline.} =
    message.options

proc `options=`*(message: google_protobuf_Method, value: seq[google_protobuf_Option]) {.inline.} =
    setoptions(message, value)

proc clearsyntax*(message: google_protobuf_Method) =
    message.syntax = google_protobuf_Syntax.SYNTAX_PROTO2

proc setsyntax*(message: google_protobuf_Method, value: google_protobuf_Syntax) =
    message.syntax = value

proc syntax*(message: google_protobuf_Method): google_protobuf_Syntax {.inline.} =
    message.syntax

proc `syntax=`*(message: google_protobuf_Method, value: google_protobuf_Syntax) {.inline.} =
    setsyntax(message, value)

proc sizeOfgoogle_protobuf_Method*(message: google_protobuf_Method): uint64 =
    if len(message.name) > 0:
        result = result + sizeOfTag(1, WireType.LengthDelimited)
        result = result + sizeOfString(message.name)
    if len(message.requestTypeUrl) > 0:
        result = result + sizeOfTag(2, WireType.LengthDelimited)
        result = result + sizeOfString(message.requestTypeUrl)
    if message.requestStreaming != false:
        result = result + sizeOfTag(3, WireType.Varint)
        result = result + sizeOfBool(message.requestStreaming)
    if len(message.responseTypeUrl) > 0:
        result = result + sizeOfTag(4, WireType.LengthDelimited)
        result = result + sizeOfString(message.responseTypeUrl)
    if message.responseStreaming != false:
        result = result + sizeOfTag(5, WireType.Varint)
        result = result + sizeOfBool(message.responseStreaming)
    for value in message.options:
        result = result + sizeOfTag(6, WireType.LengthDelimited)
        result = result + sizeOfLengthDelimited(sizeOfgoogle_protobuf_Option(value))
    if message.syntax != google_protobuf_Syntax.SYNTAX_PROTO2:
        result = result + sizeOfTag(7, WireType.Varint)
        result = result + sizeOfEnum[google_protobuf_Syntax](message.syntax)
    result = result + sizeOfUnknownFields(message)

proc writegoogle_protobuf_Method*(stream: Stream, message: google_protobuf_Method) =
    if len(message.name) > 0:
        protoWriteString(stream, message.name, 1)
    if len(message.requestTypeUrl) > 0:
        protoWriteString(stream, message.requestTypeUrl, 2)
    if message.requestStreaming != false:
        protoWriteBool(stream, message.requestStreaming, 3)
    if len(message.responseTypeUrl) > 0:
        protoWriteString(stream, message.responseTypeUrl, 4)
    if message.responseStreaming != false:
        protoWriteBool(stream, message.responseStreaming, 5)
    for value in message.options:
        writeMessage(stream, value, 6)
    if message.syntax != google_protobuf_Syntax.SYNTAX_PROTO2:
        protoWriteEnum(stream, message.syntax, 7)
    writeUnknownFields(stream, message)

proc readgoogle_protobuf_Method*(stream: Stream): google_protobuf_Method =
    result = newgoogle_protobuf_Method()
    while not atEnd(stream):
        let
            tag = readTag(stream)
            wireType = wireType(tag)
        case fieldNumber(tag)
        of 0:
            raise newException(InvalidFieldNumberError, "Invalid field number: 0")
        of 1:
            expectWireType(wireType, WireType.LengthDelimited)
            setname(result, protoReadString(stream))
        of 2:
            expectWireType(wireType, WireType.LengthDelimited)
            setrequestTypeUrl(result, protoReadString(stream))
        of 3:
            expectWireType(wireType, WireType.Varint)
            setrequestStreaming(result, protoReadBool(stream))
        of 4:
            expectWireType(wireType, WireType.LengthDelimited)
            setresponseTypeUrl(result, protoReadString(stream))
        of 5:
            expectWireType(wireType, WireType.Varint)
            setresponseStreaming(result, protoReadBool(stream))
        of 6:
            expectWireType(wireType, WireType.LengthDelimited)
            let data = readLengthDelimited(stream)
            addoptions(result, newgoogle_protobuf_Option(data))
        of 7:
            expectWireType(wireType, WireType.Varint)
            setsyntax(result, protoReadEnum[google_protobuf_Syntax](stream))
        else: readUnknownField(stream, result, tag)

proc toJson*(message: google_protobuf_Method): JsonNode =
    result = newJObject()
    if len(message.name) > 0:
        result["name"] = %message.name
    if len(message.requestTypeUrl) > 0:
        result["requestTypeUrl"] = %message.requestTypeUrl
    if message.requestStreaming != false:
        result["requestStreaming"] = %message.requestStreaming
    if len(message.responseTypeUrl) > 0:
        result["responseTypeUrl"] = %message.responseTypeUrl
    if message.responseStreaming != false:
        result["responseStreaming"] = %message.responseStreaming
    if len(message.options) > 0:
        let arr = newJArray()
        for value in message.options:
            add(arr, toJson(value))
        result["options"] = arr
    if message.syntax != google_protobuf_Syntax.SYNTAX_PROTO2:
        result["syntax"] = toJson(message.syntax)

proc parsegoogle_protobuf_Method*(obj: JsonNode): google_protobuf_Method =
    result = newgoogle_protobuf_Method()
    var node: JsonNode
    if obj.kind != JObject:
        raise newException(nimpb_json.ParseError, "object expected")
    node = getJsonField(obj, "name", "name")
    if node != nil and node.kind != JNull:
        setname(result, parseString(node))
    node = getJsonField(obj, "request_type_url", "requestTypeUrl")
    if node != nil and node.kind != JNull:
        setrequestTypeUrl(result, parseString(node))
    node = getJsonField(obj, "request_streaming", "requestStreaming")
    if node != nil and node.kind != JNull:
        setrequestStreaming(result, parseBool(node))
    node = getJsonField(obj, "response_type_url", "responseTypeUrl")
    if node != nil and node.kind != JNull:
        setresponseTypeUrl(result, parseString(node))
    node = getJsonField(obj, "response_streaming", "responseStreaming")
    if node != nil and node.kind != JNull:
        setresponseStreaming(result, parseBool(node))
    node = getJsonField(obj, "options", "options")
    if node != nil and node.kind != JNull:
        if node.kind != JArray:
            raise newException(ValueError, "not an array")
        for value in node:
            addoptions(result, parsegoogle_protobuf_Option(value))
    node = getJsonField(obj, "syntax", "syntax")
    if node != nil and node.kind != JNull:
        setsyntax(result, parseEnum[google_protobuf_Syntax](node))

proc serialize*(message: google_protobuf_Method): string =
    let
        ss = newStringStream()
    writegoogle_protobuf_Method(ss, message)
    result = ss.data

proc newgoogle_protobuf_Method*(data: string): google_protobuf_Method =
    let
        ss = newStringStream(data)
    result = readgoogle_protobuf_Method(ss)

proc newgoogle_protobuf_Method*(data: seq[byte]): google_protobuf_Method =
    let
        ss = newStringStream(cast[string](data))
    result = readgoogle_protobuf_Method(ss)


proc fullyQualifiedName*(T: typedesc[google_protobuf_Mixin]): string = "google.protobuf.Mixin"

proc readgoogle_protobuf_MixinImpl(stream: Stream): Message = readgoogle_protobuf_Mixin(stream)
proc writegoogle_protobuf_MixinImpl(stream: Stream, msg: Message) = writegoogle_protobuf_Mixin(stream, google_protobuf_Mixin(msg))
proc toJsongoogle_protobuf_MixinImpl(msg: Message): JsonNode = toJson(google_protobuf_Mixin(msg))
proc fromJsongoogle_protobuf_MixinImpl(node: JsonNode): Message = parsegoogle_protobuf_Mixin(node)

proc google_protobuf_MixinProcs*(): MessageProcs =
    result.readImpl = readgoogle_protobuf_MixinImpl
    result.writeImpl = writegoogle_protobuf_MixinImpl
    result.toJsonImpl = toJsongoogle_protobuf_MixinImpl
    result.fromJsonImpl = fromJsongoogle_protobuf_MixinImpl

proc newgoogle_protobuf_Mixin*(): google_protobuf_Mixin =
    new(result)
    initMessage(result[])
    result.procs = google_protobuf_MixinProcs()
    result.name = ""
    result.root = ""

proc clearname*(message: google_protobuf_Mixin) =
    message.name = ""

proc setname*(message: google_protobuf_Mixin, value: string) =
    message.name = value

proc name*(message: google_protobuf_Mixin): string {.inline.} =
    message.name

proc `name=`*(message: google_protobuf_Mixin, value: string) {.inline.} =
    setname(message, value)

proc clearroot*(message: google_protobuf_Mixin) =
    message.root = ""

proc setroot*(message: google_protobuf_Mixin, value: string) =
    message.root = value

proc root*(message: google_protobuf_Mixin): string {.inline.} =
    message.root

proc `root=`*(message: google_protobuf_Mixin, value: string) {.inline.} =
    setroot(message, value)

proc sizeOfgoogle_protobuf_Mixin*(message: google_protobuf_Mixin): uint64 =
    if len(message.name) > 0:
        result = result + sizeOfTag(1, WireType.LengthDelimited)
        result = result + sizeOfString(message.name)
    if len(message.root) > 0:
        result = result + sizeOfTag(2, WireType.LengthDelimited)
        result = result + sizeOfString(message.root)
    result = result + sizeOfUnknownFields(message)

proc writegoogle_protobuf_Mixin*(stream: Stream, message: google_protobuf_Mixin) =
    if len(message.name) > 0:
        protoWriteString(stream, message.name, 1)
    if len(message.root) > 0:
        protoWriteString(stream, message.root, 2)
    writeUnknownFields(stream, message)

proc readgoogle_protobuf_Mixin*(stream: Stream): google_protobuf_Mixin =
    result = newgoogle_protobuf_Mixin()
    while not atEnd(stream):
        let
            tag = readTag(stream)
            wireType = wireType(tag)
        case fieldNumber(tag)
        of 0:
            raise newException(InvalidFieldNumberError, "Invalid field number: 0")
        of 1:
            expectWireType(wireType, WireType.LengthDelimited)
            setname(result, protoReadString(stream))
        of 2:
            expectWireType(wireType, WireType.LengthDelimited)
            setroot(result, protoReadString(stream))
        else: readUnknownField(stream, result, tag)

proc toJson*(message: google_protobuf_Mixin): JsonNode =
    result = newJObject()
    if len(message.name) > 0:
        result["name"] = %message.name
    if len(message.root) > 0:
        result["root"] = %message.root

proc parsegoogle_protobuf_Mixin*(obj: JsonNode): google_protobuf_Mixin =
    result = newgoogle_protobuf_Mixin()
    var node: JsonNode
    if obj.kind != JObject:
        raise newException(nimpb_json.ParseError, "object expected")
    node = getJsonField(obj, "name", "name")
    if node != nil and node.kind != JNull:
        setname(result, parseString(node))
    node = getJsonField(obj, "root", "root")
    if node != nil and node.kind != JNull:
        setroot(result, parseString(node))

proc serialize*(message: google_protobuf_Mixin): string =
    let
        ss = newStringStream()
    writegoogle_protobuf_Mixin(ss, message)
    result = ss.data

proc newgoogle_protobuf_Mixin*(data: string): google_protobuf_Mixin =
    let
        ss = newStringStream(data)
    result = readgoogle_protobuf_Mixin(ss)

proc newgoogle_protobuf_Mixin*(data: seq[byte]): google_protobuf_Mixin =
    let
        ss = newStringStream(cast[string](data))
    result = readgoogle_protobuf_Mixin(ss)


proc fullyQualifiedName*(T: typedesc[google_protobuf_Api]): string = "google.protobuf.Api"

proc readgoogle_protobuf_ApiImpl(stream: Stream): Message = readgoogle_protobuf_Api(stream)
proc writegoogle_protobuf_ApiImpl(stream: Stream, msg: Message) = writegoogle_protobuf_Api(stream, google_protobuf_Api(msg))
proc toJsongoogle_protobuf_ApiImpl(msg: Message): JsonNode = toJson(google_protobuf_Api(msg))
proc fromJsongoogle_protobuf_ApiImpl(node: JsonNode): Message = parsegoogle_protobuf_Api(node)

proc google_protobuf_ApiProcs*(): MessageProcs =
    result.readImpl = readgoogle_protobuf_ApiImpl
    result.writeImpl = writegoogle_protobuf_ApiImpl
    result.toJsonImpl = toJsongoogle_protobuf_ApiImpl
    result.fromJsonImpl = fromJsongoogle_protobuf_ApiImpl

proc newgoogle_protobuf_Api*(): google_protobuf_Api =
    new(result)
    initMessage(result[])
    result.procs = google_protobuf_ApiProcs()
    result.name = ""
    result.methods = @[]
    result.options = @[]
    result.version = ""
    result.sourceContext = nil
    result.mixins = @[]
    result.syntax = google_protobuf_Syntax.SYNTAX_PROTO2

proc clearname*(message: google_protobuf_Api) =
    message.name = ""

proc setname*(message: google_protobuf_Api, value: string) =
    message.name = value

proc name*(message: google_protobuf_Api): string {.inline.} =
    message.name

proc `name=`*(message: google_protobuf_Api, value: string) {.inline.} =
    setname(message, value)

proc clearmethods*(message: google_protobuf_Api) =
    message.methods = @[]
    clearFields(message, [2])

proc hasmethods*(message: google_protobuf_Api): bool =
    result = hasField(message, 2) or (len(message.methods) > 0)

proc setmethods*(message: google_protobuf_Api, value: seq[google_protobuf_Method]) =
    message.methods = value
    setField(message, 2)

proc addmethods*(message: google_protobuf_Api, value: google_protobuf_Method) =
    add(message.methods, value)

proc methods*(message: google_protobuf_Api): seq[google_protobuf_Method] {.inline.} =
    message.methods

proc `methods=`*(message: google_protobuf_Api, value: seq[google_protobuf_Method]) {.inline.} =
    setmethods(message, value)

proc clearoptions*(message: google_protobuf_Api) =
    message.options = @[]
    clearFields(message, [3])

proc hasoptions*(message: google_protobuf_Api): bool =
    result = hasField(message, 3) or (len(message.options) > 0)

proc setoptions*(message: google_protobuf_Api, value: seq[google_protobuf_Option]) =
    message.options = value
    setField(message, 3)

proc addoptions*(message: google_protobuf_Api, value: google_protobuf_Option) =
    add(message.options, value)

proc options*(message: google_protobuf_Api): seq[google_protobuf_Option] {.inline.} =
    message.options

proc `options=`*(message: google_protobuf_Api, value: seq[google_protobuf_Option]) {.inline.} =
    setoptions(message, value)

proc clearversion*(message: google_protobuf_Api) =
    message.version = ""

proc setversion*(message: google_protobuf_Api, value: string) =
    message.version = value

proc version*(message: google_protobuf_Api): string {.inline.} =
    message.version

proc `version=`*(message: google_protobuf_Api, value: string) {.inline.} =
    setversion(message, value)

proc clearsourceContext*(message: google_protobuf_Api) =
    message.sourceContext = nil
    clearFields(message, [5])

proc hassourceContext*(message: google_protobuf_Api): bool =
    result = hasField(message, 5)

proc setsourceContext*(message: google_protobuf_Api, value: google_protobuf_SourceContext) =
    message.sourceContext = value
    setField(message, 5)

proc sourceContext*(message: google_protobuf_Api): google_protobuf_SourceContext {.inline.} =
    message.sourceContext

proc `sourceContext=`*(message: google_protobuf_Api, value: google_protobuf_SourceContext) {.inline.} =
    setsourceContext(message, value)

proc clearmixins*(message: google_protobuf_Api) =
    message.mixins = @[]
    clearFields(message, [6])

proc hasmixins*(message: google_protobuf_Api): bool =
    result = hasField(message, 6) or (len(message.mixins) > 0)

proc setmixins*(message: google_protobuf_Api, value: seq[google_protobuf_Mixin]) =
    message.mixins = value
    setField(message, 6)

proc addmixins*(message: google_protobuf_Api, value: google_protobuf_Mixin) =
    add(message.mixins, value)

proc mixins*(message: google_protobuf_Api): seq[google_protobuf_Mixin] {.inline.} =
    message.mixins

proc `mixins=`*(message: google_protobuf_Api, value: seq[google_protobuf_Mixin]) {.inline.} =
    setmixins(message, value)

proc clearsyntax*(message: google_protobuf_Api) =
    message.syntax = google_protobuf_Syntax.SYNTAX_PROTO2

proc setsyntax*(message: google_protobuf_Api, value: google_protobuf_Syntax) =
    message.syntax = value

proc syntax*(message: google_protobuf_Api): google_protobuf_Syntax {.inline.} =
    message.syntax

proc `syntax=`*(message: google_protobuf_Api, value: google_protobuf_Syntax) {.inline.} =
    setsyntax(message, value)

proc sizeOfgoogle_protobuf_Api*(message: google_protobuf_Api): uint64 =
    if len(message.name) > 0:
        result = result + sizeOfTag(1, WireType.LengthDelimited)
        result = result + sizeOfString(message.name)
    for value in message.methods:
        result = result + sizeOfTag(2, WireType.LengthDelimited)
        result = result + sizeOfLengthDelimited(sizeOfgoogle_protobuf_Method(value))
    for value in message.options:
        result = result + sizeOfTag(3, WireType.LengthDelimited)
        result = result + sizeOfLengthDelimited(sizeOfgoogle_protobuf_Option(value))
    if len(message.version) > 0:
        result = result + sizeOfTag(4, WireType.LengthDelimited)
        result = result + sizeOfString(message.version)
    if hassourceContext(message):
        result = result + sizeOfTag(5, WireType.LengthDelimited)
        result = result + sizeOfLengthDelimited(sizeOfgoogle_protobuf_SourceContext(message.sourceContext))
    for value in message.mixins:
        result = result + sizeOfTag(6, WireType.LengthDelimited)
        result = result + sizeOfLengthDelimited(sizeOfgoogle_protobuf_Mixin(value))
    if message.syntax != google_protobuf_Syntax.SYNTAX_PROTO2:
        result = result + sizeOfTag(7, WireType.Varint)
        result = result + sizeOfEnum[google_protobuf_Syntax](message.syntax)
    result = result + sizeOfUnknownFields(message)

proc writegoogle_protobuf_Api*(stream: Stream, message: google_protobuf_Api) =
    if len(message.name) > 0:
        protoWriteString(stream, message.name, 1)
    for value in message.methods:
        writeMessage(stream, value, 2)
    for value in message.options:
        writeMessage(stream, value, 3)
    if len(message.version) > 0:
        protoWriteString(stream, message.version, 4)
    if hassourceContext(message):
        writeMessage(stream, message.sourceContext, 5)
    for value in message.mixins:
        writeMessage(stream, value, 6)
    if message.syntax != google_protobuf_Syntax.SYNTAX_PROTO2:
        protoWriteEnum(stream, message.syntax, 7)
    writeUnknownFields(stream, message)

proc readgoogle_protobuf_Api*(stream: Stream): google_protobuf_Api =
    result = newgoogle_protobuf_Api()
    while not atEnd(stream):
        let
            tag = readTag(stream)
            wireType = wireType(tag)
        case fieldNumber(tag)
        of 0:
            raise newException(InvalidFieldNumberError, "Invalid field number: 0")
        of 1:
            expectWireType(wireType, WireType.LengthDelimited)
            setname(result, protoReadString(stream))
        of 2:
            expectWireType(wireType, WireType.LengthDelimited)
            let data = readLengthDelimited(stream)
            addmethods(result, newgoogle_protobuf_Method(data))
        of 3:
            expectWireType(wireType, WireType.LengthDelimited)
            let data = readLengthDelimited(stream)
            addoptions(result, newgoogle_protobuf_Option(data))
        of 4:
            expectWireType(wireType, WireType.LengthDelimited)
            setversion(result, protoReadString(stream))
        of 5:
            expectWireType(wireType, WireType.LengthDelimited)
            let data = readLengthDelimited(stream)
            setsourceContext(result, newgoogle_protobuf_SourceContext(data))
        of 6:
            expectWireType(wireType, WireType.LengthDelimited)
            let data = readLengthDelimited(stream)
            addmixins(result, newgoogle_protobuf_Mixin(data))
        of 7:
            expectWireType(wireType, WireType.Varint)
            setsyntax(result, protoReadEnum[google_protobuf_Syntax](stream))
        else: readUnknownField(stream, result, tag)

proc toJson*(message: google_protobuf_Api): JsonNode =
    result = newJObject()
    if len(message.name) > 0:
        result["name"] = %message.name
    if len(message.methods) > 0:
        let arr = newJArray()
        for value in message.methods:
            add(arr, toJson(value))
        result["methods"] = arr
    if len(message.options) > 0:
        let arr = newJArray()
        for value in message.options:
            add(arr, toJson(value))
        result["options"] = arr
    if len(message.version) > 0:
        result["version"] = %message.version
    if hassourceContext(message):
        result["sourceContext"] = toJson(message.sourceContext)
    if len(message.mixins) > 0:
        let arr = newJArray()
        for value in message.mixins:
            add(arr, toJson(value))
        result["mixins"] = arr
    if message.syntax != google_protobuf_Syntax.SYNTAX_PROTO2:
        result["syntax"] = toJson(message.syntax)

proc parsegoogle_protobuf_Api*(obj: JsonNode): google_protobuf_Api =
    result = newgoogle_protobuf_Api()
    var node: JsonNode
    if obj.kind != JObject:
        raise newException(nimpb_json.ParseError, "object expected")
    node = getJsonField(obj, "name", "name")
    if node != nil and node.kind != JNull:
        setname(result, parseString(node))
    node = getJsonField(obj, "methods", "methods")
    if node != nil and node.kind != JNull:
        if node.kind != JArray:
            raise newException(ValueError, "not an array")
        for value in node:
            addmethods(result, parsegoogle_protobuf_Method(value))
    node = getJsonField(obj, "options", "options")
    if node != nil and node.kind != JNull:
        if node.kind != JArray:
            raise newException(ValueError, "not an array")
        for value in node:
            addoptions(result, parsegoogle_protobuf_Option(value))
    node = getJsonField(obj, "version", "version")
    if node != nil and node.kind != JNull:
        setversion(result, parseString(node))
    node = getJsonField(obj, "source_context", "sourceContext")
    if node != nil and node.kind != JNull:
        setsourceContext(result, parsegoogle_protobuf_SourceContext(node))
    node = getJsonField(obj, "mixins", "mixins")
    if node != nil and node.kind != JNull:
        if node.kind != JArray:
            raise newException(ValueError, "not an array")
        for value in node:
            addmixins(result, parsegoogle_protobuf_Mixin(value))
    node = getJsonField(obj, "syntax", "syntax")
    if node != nil and node.kind != JNull:
        setsyntax(result, parseEnum[google_protobuf_Syntax](node))

proc serialize*(message: google_protobuf_Api): string =
    let
        ss = newStringStream()
    writegoogle_protobuf_Api(ss, message)
    result = ss.data

proc newgoogle_protobuf_Api*(data: string): google_protobuf_Api =
    let
        ss = newStringStream(data)
    result = readgoogle_protobuf_Api(ss)

proc newgoogle_protobuf_Api*(data: seq[byte]): google_protobuf_Api =
    let
        ss = newStringStream(cast[string](data))
    result = readgoogle_protobuf_Api(ss)


