# Generated by protoc_gen_nim. Do not edit!

import base64
import intsets
import json
import strutils

import nimpb/nimpb
import nimpb/json as nimpb_json

type
    google_protobuf_Empty* = ref google_protobuf_EmptyObj
    google_protobuf_EmptyObj* = object of Message

proc newgoogle_protobuf_Empty*(): google_protobuf_Empty
proc newgoogle_protobuf_Empty*(data: string): google_protobuf_Empty
proc newgoogle_protobuf_Empty*(data: seq[byte]): google_protobuf_Empty
proc writegoogle_protobuf_Empty*(stream: Stream, message: google_protobuf_Empty)
proc readgoogle_protobuf_Empty*(stream: Stream): google_protobuf_Empty
proc sizeOfgoogle_protobuf_Empty*(message: google_protobuf_Empty): uint64
proc toJson*(message: google_protobuf_Empty): JsonNode
proc parsegoogle_protobuf_Empty*(obj: JsonNode): google_protobuf_Empty

proc fullyQualifiedName*(T: typedesc[google_protobuf_Empty]): string = "google.protobuf.Empty"

proc readgoogle_protobuf_EmptyImpl(stream: Stream): Message = readgoogle_protobuf_Empty(stream)
proc writegoogle_protobuf_EmptyImpl(stream: Stream, msg: Message) = writegoogle_protobuf_Empty(stream, google_protobuf_Empty(msg))
proc toJsongoogle_protobuf_EmptyImpl(msg: Message): JsonNode = toJson(google_protobuf_Empty(msg))
proc fromJsongoogle_protobuf_EmptyImpl(node: JsonNode): Message = parsegoogle_protobuf_Empty(node)

proc google_protobuf_EmptyProcs*(): MessageProcs =
    result.readImpl = readgoogle_protobuf_EmptyImpl
    result.writeImpl = writegoogle_protobuf_EmptyImpl
    result.toJsonImpl = toJsongoogle_protobuf_EmptyImpl
    result.fromJsonImpl = fromJsongoogle_protobuf_EmptyImpl

proc newgoogle_protobuf_Empty*(): google_protobuf_Empty =
    new(result)
    initMessage(result[])
    result.procs = google_protobuf_EmptyProcs()

proc sizeOfgoogle_protobuf_Empty*(message: google_protobuf_Empty): uint64 =
    result = result + sizeOfUnknownFields(message)

proc writegoogle_protobuf_Empty*(stream: Stream, message: google_protobuf_Empty) =
    writeUnknownFields(stream, message)

proc readgoogle_protobuf_Empty*(stream: Stream): google_protobuf_Empty =
    result = newgoogle_protobuf_Empty()
    while not atEnd(stream):
        let
            tag = readTag(stream)
            wireType = wireType(tag)
        case fieldNumber(tag)
        of 0:
            raise newException(InvalidFieldNumberError, "Invalid field number: 0")
        else: readUnknownField(stream, result, tag)

proc toJson*(message: google_protobuf_Empty): JsonNode =
    result = newJObject()

proc parsegoogle_protobuf_Empty*(obj: JsonNode): google_protobuf_Empty =
    result = newgoogle_protobuf_Empty()
    var node: JsonNode
    if obj.kind != JObject:
        raise newException(nimpb_json.ParseError, "object expected")

proc serialize*(message: google_protobuf_Empty): string =
    let
        ss = newStringStream()
    writegoogle_protobuf_Empty(ss, message)
    result = ss.data

proc newgoogle_protobuf_Empty*(data: string): google_protobuf_Empty =
    let
        ss = newStringStream(data)
    result = readgoogle_protobuf_Empty(ss)

proc newgoogle_protobuf_Empty*(data: seq[byte]): google_protobuf_Empty =
    let
        ss = newStringStream(cast[string](data))
    result = readgoogle_protobuf_Empty(ss)


