# Generated by protoc_gen_nim. Do not edit!

import base64
import intsets
import json
import strutils

import nimpb/nimpb
import nimpb/json as nimpb_json

type
    google_protobuf_SourceContext* = ref google_protobuf_SourceContextObj
    google_protobuf_SourceContextObj* = object of Message
        fileName: string

proc newgoogle_protobuf_SourceContext*(): google_protobuf_SourceContext
proc newgoogle_protobuf_SourceContext*(data: string): google_protobuf_SourceContext
proc newgoogle_protobuf_SourceContext*(data: seq[byte]): google_protobuf_SourceContext
proc writegoogle_protobuf_SourceContext*(stream: Stream, message: google_protobuf_SourceContext)
proc readgoogle_protobuf_SourceContext*(stream: Stream): google_protobuf_SourceContext
proc sizeOfgoogle_protobuf_SourceContext*(message: google_protobuf_SourceContext): uint64
proc toJson*(message: google_protobuf_SourceContext): JsonNode
proc parsegoogle_protobuf_SourceContext*(obj: JsonNode): google_protobuf_SourceContext

proc newgoogle_protobuf_SourceContext*(): google_protobuf_SourceContext =
    new(result)
    initMessage(result[])
    result.fileName = ""

proc clearfileName*(message: google_protobuf_SourceContext) =
    message.fileName = ""

proc setfileName*(message: google_protobuf_SourceContext, value: string) =
    message.fileName = value

proc fileName*(message: google_protobuf_SourceContext): string {.inline.} =
    message.fileName

proc `fileName=`*(message: google_protobuf_SourceContext, value: string) {.inline.} =
    setfileName(message, value)

proc sizeOfgoogle_protobuf_SourceContext*(message: google_protobuf_SourceContext): uint64 =
    if len(message.fileName) > 0:
        result = result + sizeOfTag(1, WireType.LengthDelimited)
        result = result + sizeOfString(message.fileName)
    result = result + sizeOfUnknownFields(message)

proc writegoogle_protobuf_SourceContext*(stream: Stream, message: google_protobuf_SourceContext) =
    if len(message.fileName) > 0:
        protoWriteString(stream, message.fileName, 1)
    writeUnknownFields(stream, message)

proc readgoogle_protobuf_SourceContext*(stream: Stream): google_protobuf_SourceContext =
    result = newgoogle_protobuf_SourceContext()
    while not atEnd(stream):
        let
            tag = readTag(stream)
            wireType = wireType(tag)
        case fieldNumber(tag)
        of 0:
            raise newException(InvalidFieldNumberError, "Invalid field number: 0")
        of 1:
            expectWireType(wireType, WireType.LengthDelimited)
            setfileName(result, protoReadString(stream))
        else: readUnknownField(stream, result, tag)

proc toJson*(message: google_protobuf_SourceContext): JsonNode =
    result = newJObject()
    if len(message.fileName) > 0:
        result["fileName"] = %message.fileName

proc parsegoogle_protobuf_SourceContext*(obj: JsonNode): google_protobuf_SourceContext =
    result = newgoogle_protobuf_SourceContext()
    var node: JsonNode
    if obj.kind != JObject:
        raise newException(nimpb_json.ParseError, "object expected")
    node = getJsonField(obj, "file_name", "fileName")
    if node != nil and node.kind != JNull:
        setfileName(result, parseString(node))

proc serialize*(message: google_protobuf_SourceContext): string =
    let
        ss = newStringStream()
    writegoogle_protobuf_SourceContext(ss, message)
    result = ss.data

proc newgoogle_protobuf_SourceContext*(data: string): google_protobuf_SourceContext =
    let
        ss = newStringStream(data)
    result = readgoogle_protobuf_SourceContext(ss)

proc newgoogle_protobuf_SourceContext*(data: seq[byte]): google_protobuf_SourceContext =
    let
        ss = newStringStream(cast[string](data))
    result = readgoogle_protobuf_SourceContext(ss)


