# Generated by protoc_gen_nim. Do not edit!

import base64
import intsets
import json
import strutils
import tables
export tables

import nimpb/nimpb
import nimpb/json as nimpb_json

type
    google_protobuf_NullValue* {.pure.} = enum
        NULL_VALUE = 0
    google_protobuf_Struct* = ref google_protobuf_StructObj
    google_protobuf_StructObj* = object of Message
        fields: TableRef[string, google_protobuf_Value]
    google_protobuf_Value* = ref google_protobuf_ValueObj
    google_protobuf_ValueObj* = object of Message
        kind: google_protobuf_Value_kind_OneOf

    google_protobuf_Value_kind_Kind* {.pure.} = enum
        NullValue
        NumberValue
        StringValue
        BoolValue
        StructValue
        ListValue
        NotSet

    google_protobuf_Value_kind_OneOf* = object
        case kind*: google_protobuf_Value_kind_Kind
        of google_protobuf_Value_kind_Kind.NullValue: nullValue*: google_protobuf_NullValue
        of google_protobuf_Value_kind_Kind.NumberValue: numberValue*: float64
        of google_protobuf_Value_kind_Kind.StringValue: stringValue*: string
        of google_protobuf_Value_kind_Kind.BoolValue: boolValue*: bool
        of google_protobuf_Value_kind_Kind.StructValue: structValue*: google_protobuf_Struct
        of google_protobuf_Value_kind_Kind.ListValue: listValue*: google_protobuf_ListValue
        of google_protobuf_Value_kind_Kind.NotSet: nil
    google_protobuf_ListValue* = ref google_protobuf_ListValueObj
    google_protobuf_ListValueObj* = object of Message
        values: seq[google_protobuf_Value]

proc newgoogle_protobuf_Struct*(): google_protobuf_Struct
proc newgoogle_protobuf_Struct*(data: string): google_protobuf_Struct
proc newgoogle_protobuf_Struct*(data: seq[byte]): google_protobuf_Struct
proc writegoogle_protobuf_Struct*(stream: Stream, message: google_protobuf_Struct)
proc readgoogle_protobuf_Struct*(stream: Stream): google_protobuf_Struct
proc sizeOfgoogle_protobuf_Struct*(message: google_protobuf_Struct): uint64

proc newgoogle_protobuf_ListValue*(): google_protobuf_ListValue
proc newgoogle_protobuf_ListValue*(data: string): google_protobuf_ListValue
proc newgoogle_protobuf_ListValue*(data: seq[byte]): google_protobuf_ListValue
proc writegoogle_protobuf_ListValue*(stream: Stream, message: google_protobuf_ListValue)
proc readgoogle_protobuf_ListValue*(stream: Stream): google_protobuf_ListValue
proc sizeOfgoogle_protobuf_ListValue*(message: google_protobuf_ListValue): uint64

proc newgoogle_protobuf_Value*(): google_protobuf_Value
proc newgoogle_protobuf_Value*(data: string): google_protobuf_Value
proc newgoogle_protobuf_Value*(data: seq[byte]): google_protobuf_Value
proc writegoogle_protobuf_Value*(stream: Stream, message: google_protobuf_Value)
proc readgoogle_protobuf_Value*(stream: Stream): google_protobuf_Value
proc sizeOfgoogle_protobuf_Value*(message: google_protobuf_Value): uint64

proc writegoogle_protobuf_Struct_FieldsEntryKV(stream: Stream, key: string, value: google_protobuf_Value)
proc readgoogle_protobuf_Struct_FieldsEntryKV(stream: Stream, tbl: TableRef[string, google_protobuf_Value])
proc sizeOfgoogle_protobuf_Struct_FieldsEntryKV(key: string, value: google_protobuf_Value): uint64

proc fullyQualifiedName*(T: typedesc[google_protobuf_Struct]): string = "google.protobuf.Struct"

proc readgoogle_protobuf_StructImpl(stream: Stream): Message = readgoogle_protobuf_Struct(stream)
proc writegoogle_protobuf_StructImpl(stream: Stream, msg: Message) = writegoogle_protobuf_Struct(stream, google_protobuf_Struct(msg))

proc google_protobuf_StructProcs*(): MessageProcs =
    result.readImpl = readgoogle_protobuf_StructImpl
    result.writeImpl = writegoogle_protobuf_StructImpl

proc newgoogle_protobuf_Struct*(): google_protobuf_Struct =
    new(result)
    initMessage(result[])
    result.procs = google_protobuf_StructProcs()
    result.fields = newTable[string, google_protobuf_Value]()

proc clearfields*(message: google_protobuf_Struct) =
    message.fields = newTable[string, google_protobuf_Value]()

proc setfields*(message: google_protobuf_Struct, value: TableRef[string, google_protobuf_Value]) =
    message.fields = value

proc fields*(message: google_protobuf_Struct): TableRef[string, google_protobuf_Value] {.inline.} =
    message.fields

proc `fields=`*(message: google_protobuf_Struct, value: TableRef[string, google_protobuf_Value]) {.inline.} =
    setfields(message, value)

proc sizeOfgoogle_protobuf_Struct*(message: google_protobuf_Struct): uint64 =
    if len(message.fields) > 0:
        var sizeOfKV = 0'u64
        for key, value in message.fields:
            sizeOfKV = sizeOfKV + sizeOfgoogle_protobuf_Struct_FieldsEntryKV(key, value)
        result = result + sizeOfTag(1, WireType.LengthDelimited)
        result = result + sizeOfLengthDelimited(sizeOfKV)
    result = result + sizeOfUnknownFields(message)

proc writegoogle_protobuf_Struct*(stream: Stream, message: google_protobuf_Struct) =
    for key, value in message.fields:
        writeTag(stream, 1, WireType.LengthDelimited)
        writeVarint(stream, sizeOfgoogle_protobuf_Struct_FieldsEntryKV(key, value))
        writegoogle_protobuf_Struct_FieldsEntryKV(stream, key, value)
    writeUnknownFields(stream, message)

proc readgoogle_protobuf_Struct*(stream: Stream): google_protobuf_Struct =
    result = newgoogle_protobuf_Struct()
    while not atEnd(stream):
        let
            tag = readTag(stream)
            wireType = wireType(tag)
        case fieldNumber(tag)
        of 0:
            raise newException(InvalidFieldNumberError, "Invalid field number: 0")
        of 1:
            expectWireType(wireType, WireType.LengthDelimited)
            let
                size = readVarint(stream)
                data = safeReadStr(stream, int(size))
                pbs = newStringStream(data)
            readgoogle_protobuf_Struct_FieldsEntryKV(pbs, result.fields)
        else: readUnknownField(stream, result, tag)

proc serialize*(message: google_protobuf_Struct): string =
    let
        ss = newStringStream()
    writegoogle_protobuf_Struct(ss, message)
    result = ss.data

proc newgoogle_protobuf_Struct*(data: string): google_protobuf_Struct =
    let
        ss = newStringStream(data)
    result = readgoogle_protobuf_Struct(ss)

proc newgoogle_protobuf_Struct*(data: seq[byte]): google_protobuf_Struct =
    let
        ss = newStringStream(cast[string](data))
    result = readgoogle_protobuf_Struct(ss)


proc fullyQualifiedName*(T: typedesc[google_protobuf_ListValue]): string = "google.protobuf.ListValue"

proc readgoogle_protobuf_ListValueImpl(stream: Stream): Message = readgoogle_protobuf_ListValue(stream)
proc writegoogle_protobuf_ListValueImpl(stream: Stream, msg: Message) = writegoogle_protobuf_ListValue(stream, google_protobuf_ListValue(msg))

proc google_protobuf_ListValueProcs*(): MessageProcs =
    result.readImpl = readgoogle_protobuf_ListValueImpl
    result.writeImpl = writegoogle_protobuf_ListValueImpl

proc newgoogle_protobuf_ListValue*(): google_protobuf_ListValue =
    new(result)
    initMessage(result[])
    result.procs = google_protobuf_ListValueProcs()
    result.values = @[]

proc clearvalues*(message: google_protobuf_ListValue) =
    message.values = @[]
    clearFields(message, [1])

proc hasvalues*(message: google_protobuf_ListValue): bool =
    result = hasField(message, 1) or (len(message.values) > 0)

proc setvalues*(message: google_protobuf_ListValue, value: seq[google_protobuf_Value]) =
    message.values = value
    setField(message, 1)

proc addvalues*(message: google_protobuf_ListValue, value: google_protobuf_Value) =
    add(message.values, value)

proc values*(message: google_protobuf_ListValue): seq[google_protobuf_Value] {.inline.} =
    message.values

proc `values=`*(message: google_protobuf_ListValue, value: seq[google_protobuf_Value]) {.inline.} =
    setvalues(message, value)

proc sizeOfgoogle_protobuf_ListValue*(message: google_protobuf_ListValue): uint64 =
    for value in message.values:
        result = result + sizeOfTag(1, WireType.LengthDelimited)
        result = result + sizeOfLengthDelimited(sizeOfgoogle_protobuf_Value(value))
    result = result + sizeOfUnknownFields(message)

proc writegoogle_protobuf_ListValue*(stream: Stream, message: google_protobuf_ListValue) =
    for value in message.values:
        writeMessage(stream, value, 1)
    writeUnknownFields(stream, message)

proc readgoogle_protobuf_ListValue*(stream: Stream): google_protobuf_ListValue =
    result = newgoogle_protobuf_ListValue()
    while not atEnd(stream):
        let
            tag = readTag(stream)
            wireType = wireType(tag)
        case fieldNumber(tag)
        of 0:
            raise newException(InvalidFieldNumberError, "Invalid field number: 0")
        of 1:
            expectWireType(wireType, WireType.LengthDelimited)
            let data = readLengthDelimited(stream)
            addvalues(result, newgoogle_protobuf_Value(data))
        else: readUnknownField(stream, result, tag)

proc serialize*(message: google_protobuf_ListValue): string =
    let
        ss = newStringStream()
    writegoogle_protobuf_ListValue(ss, message)
    result = ss.data

proc newgoogle_protobuf_ListValue*(data: string): google_protobuf_ListValue =
    let
        ss = newStringStream(data)
    result = readgoogle_protobuf_ListValue(ss)

proc newgoogle_protobuf_ListValue*(data: seq[byte]): google_protobuf_ListValue =
    let
        ss = newStringStream(cast[string](data))
    result = readgoogle_protobuf_ListValue(ss)


proc fullyQualifiedName*(T: typedesc[google_protobuf_Value]): string = "google.protobuf.Value"

proc readgoogle_protobuf_ValueImpl(stream: Stream): Message = readgoogle_protobuf_Value(stream)
proc writegoogle_protobuf_ValueImpl(stream: Stream, msg: Message) = writegoogle_protobuf_Value(stream, google_protobuf_Value(msg))

proc google_protobuf_ValueProcs*(): MessageProcs =
    result.readImpl = readgoogle_protobuf_ValueImpl
    result.writeImpl = writegoogle_protobuf_ValueImpl

proc newgoogle_protobuf_Value*(): google_protobuf_Value =
    new(result)
    initMessage(result[])
    result.procs = google_protobuf_ValueProcs()
    result.kind = google_protobuf_Value_kind_OneOf(kind: google_protobuf_Value_kind_Kind.NotSet)

proc clearnullValue*(message: google_protobuf_Value) =
    reset(message.kind)
    message.kind.kind = google_protobuf_Value_kind_Kind.NotSet
    clearFields(message, [1, 2, 3, 4, 5, 6])

proc hasnullValue*(message: google_protobuf_Value): bool =
    result = hasField(message, 1)

proc setnullValue*(message: google_protobuf_Value, value: google_protobuf_NullValue) =
    if message.kind.kind != google_protobuf_Value_kind_Kind.NullValue:
        message.kind = google_protobuf_Value_kind_OneOf(kind: google_protobuf_Value_kind_Kind.NullValue, nullValue: value)
    else:
        message.kind.nullValue = value
    setField(message, 1)
    clearFields(message, [2, 3, 4, 5, 6])

proc nullValue*(message: google_protobuf_Value): google_protobuf_NullValue {.inline.} =
    message.kind.nullValue

proc `nullValue=`*(message: google_protobuf_Value, value: google_protobuf_NullValue) {.inline.} =
    setnullValue(message, value)

proc clearnumberValue*(message: google_protobuf_Value) =
    reset(message.kind)
    message.kind.kind = google_protobuf_Value_kind_Kind.NotSet
    clearFields(message, [2, 1, 3, 4, 5, 6])

proc hasnumberValue*(message: google_protobuf_Value): bool =
    result = hasField(message, 2)

proc setnumberValue*(message: google_protobuf_Value, value: float64) =
    if message.kind.kind != google_protobuf_Value_kind_Kind.NumberValue:
        message.kind = google_protobuf_Value_kind_OneOf(kind: google_protobuf_Value_kind_Kind.NumberValue, numberValue: value)
    else:
        message.kind.numberValue = value
    setField(message, 2)
    clearFields(message, [1, 3, 4, 5, 6])

proc numberValue*(message: google_protobuf_Value): float64 {.inline.} =
    message.kind.numberValue

proc `numberValue=`*(message: google_protobuf_Value, value: float64) {.inline.} =
    setnumberValue(message, value)

proc clearstringValue*(message: google_protobuf_Value) =
    reset(message.kind)
    message.kind.kind = google_protobuf_Value_kind_Kind.NotSet
    clearFields(message, [3, 1, 2, 4, 5, 6])

proc hasstringValue*(message: google_protobuf_Value): bool =
    result = hasField(message, 3)

proc setstringValue*(message: google_protobuf_Value, value: string) =
    if message.kind.kind != google_protobuf_Value_kind_Kind.StringValue:
        message.kind = google_protobuf_Value_kind_OneOf(kind: google_protobuf_Value_kind_Kind.StringValue, stringValue: value)
    else:
        message.kind.stringValue = value
    setField(message, 3)
    clearFields(message, [1, 2, 4, 5, 6])

proc stringValue*(message: google_protobuf_Value): string {.inline.} =
    message.kind.stringValue

proc `stringValue=`*(message: google_protobuf_Value, value: string) {.inline.} =
    setstringValue(message, value)

proc clearboolValue*(message: google_protobuf_Value) =
    reset(message.kind)
    message.kind.kind = google_protobuf_Value_kind_Kind.NotSet
    clearFields(message, [4, 1, 2, 3, 5, 6])

proc hasboolValue*(message: google_protobuf_Value): bool =
    result = hasField(message, 4)

proc setboolValue*(message: google_protobuf_Value, value: bool) =
    if message.kind.kind != google_protobuf_Value_kind_Kind.BoolValue:
        message.kind = google_protobuf_Value_kind_OneOf(kind: google_protobuf_Value_kind_Kind.BoolValue, boolValue: value)
    else:
        message.kind.boolValue = value
    setField(message, 4)
    clearFields(message, [1, 2, 3, 5, 6])

proc boolValue*(message: google_protobuf_Value): bool {.inline.} =
    message.kind.boolValue

proc `boolValue=`*(message: google_protobuf_Value, value: bool) {.inline.} =
    setboolValue(message, value)

proc clearstructValue*(message: google_protobuf_Value) =
    reset(message.kind)
    message.kind.kind = google_protobuf_Value_kind_Kind.NotSet
    clearFields(message, [5, 1, 2, 3, 4, 6])

proc hasstructValue*(message: google_protobuf_Value): bool =
    result = hasField(message, 5)

proc setstructValue*(message: google_protobuf_Value, value: google_protobuf_Struct) =
    if message.kind.kind != google_protobuf_Value_kind_Kind.StructValue:
        message.kind = google_protobuf_Value_kind_OneOf(kind: google_protobuf_Value_kind_Kind.StructValue, structValue: value)
    else:
        message.kind.structValue = value
    setField(message, 5)
    clearFields(message, [1, 2, 3, 4, 6])

proc structValue*(message: google_protobuf_Value): google_protobuf_Struct {.inline.} =
    message.kind.structValue

proc `structValue=`*(message: google_protobuf_Value, value: google_protobuf_Struct) {.inline.} =
    setstructValue(message, value)

proc clearlistValue*(message: google_protobuf_Value) =
    reset(message.kind)
    message.kind.kind = google_protobuf_Value_kind_Kind.NotSet
    clearFields(message, [6, 1, 2, 3, 4, 5])

proc haslistValue*(message: google_protobuf_Value): bool =
    result = hasField(message, 6)

proc setlistValue*(message: google_protobuf_Value, value: google_protobuf_ListValue) =
    if message.kind.kind != google_protobuf_Value_kind_Kind.ListValue:
        message.kind = google_protobuf_Value_kind_OneOf(kind: google_protobuf_Value_kind_Kind.ListValue, listValue: value)
    else:
        message.kind.listValue = value
    setField(message, 6)
    clearFields(message, [1, 2, 3, 4, 5])

proc listValue*(message: google_protobuf_Value): google_protobuf_ListValue {.inline.} =
    message.kind.listValue

proc `listValue=`*(message: google_protobuf_Value, value: google_protobuf_ListValue) {.inline.} =
    setlistValue(message, value)

proc sizeOfgoogle_protobuf_Value*(message: google_protobuf_Value): uint64 =
    if message.kind.kind == google_protobuf_Value_kind_Kind.NullValue:
        result = result + sizeOfTag(1, WireType.Varint)
        result = result + sizeOfEnum[google_protobuf_NullValue](message.kind.nullValue)
    if message.kind.kind == google_protobuf_Value_kind_Kind.NumberValue:
        result = result + sizeOfTag(2, WireType.Fixed64)
        result = result + sizeOfDouble(message.kind.numberValue)
    if message.kind.kind == google_protobuf_Value_kind_Kind.StringValue:
        result = result + sizeOfTag(3, WireType.LengthDelimited)
        result = result + sizeOfString(message.kind.stringValue)
    if message.kind.kind == google_protobuf_Value_kind_Kind.BoolValue:
        result = result + sizeOfTag(4, WireType.Varint)
        result = result + sizeOfBool(message.kind.boolValue)
    if message.kind.kind == google_protobuf_Value_kind_Kind.StructValue:
        result = result + sizeOfTag(5, WireType.LengthDelimited)
        result = result + sizeOfLengthDelimited(sizeOfgoogle_protobuf_Struct(message.kind.structValue))
    if message.kind.kind == google_protobuf_Value_kind_Kind.ListValue:
        result = result + sizeOfTag(6, WireType.LengthDelimited)
        result = result + sizeOfLengthDelimited(sizeOfgoogle_protobuf_ListValue(message.kind.listValue))
    result = result + sizeOfUnknownFields(message)

proc writegoogle_protobuf_Value*(stream: Stream, message: google_protobuf_Value) =
    if message.kind.kind == google_protobuf_Value_kind_Kind.NullValue:
        protoWriteEnum(stream, message.kind.nullValue, 1)
    if message.kind.kind == google_protobuf_Value_kind_Kind.NumberValue:
        protoWriteDouble(stream, message.kind.numberValue, 2)
    if message.kind.kind == google_protobuf_Value_kind_Kind.StringValue:
        protoWriteString(stream, message.kind.stringValue, 3)
    if message.kind.kind == google_protobuf_Value_kind_Kind.BoolValue:
        protoWriteBool(stream, message.kind.boolValue, 4)
    if message.kind.kind == google_protobuf_Value_kind_Kind.StructValue:
        writeMessage(stream, message.kind.structValue, 5)
    if message.kind.kind == google_protobuf_Value_kind_Kind.ListValue:
        writeMessage(stream, message.kind.listValue, 6)
    writeUnknownFields(stream, message)

proc readgoogle_protobuf_Value*(stream: Stream): google_protobuf_Value =
    result = newgoogle_protobuf_Value()
    while not atEnd(stream):
        let
            tag = readTag(stream)
            wireType = wireType(tag)
        case fieldNumber(tag)
        of 0:
            raise newException(InvalidFieldNumberError, "Invalid field number: 0")
        of 1:
            expectWireType(wireType, WireType.Varint)
            setnullValue(result, protoReadEnum[google_protobuf_NullValue](stream))
        of 2:
            expectWireType(wireType, WireType.Fixed64)
            setnumberValue(result, protoReadDouble(stream))
        of 3:
            expectWireType(wireType, WireType.LengthDelimited)
            setstringValue(result, protoReadString(stream))
        of 4:
            expectWireType(wireType, WireType.Varint)
            setboolValue(result, protoReadBool(stream))
        of 5:
            expectWireType(wireType, WireType.LengthDelimited)
            let data = readLengthDelimited(stream)
            setstructValue(result, newgoogle_protobuf_Struct(data))
        of 6:
            expectWireType(wireType, WireType.LengthDelimited)
            let data = readLengthDelimited(stream)
            setlistValue(result, newgoogle_protobuf_ListValue(data))
        else: readUnknownField(stream, result, tag)

proc serialize*(message: google_protobuf_Value): string =
    let
        ss = newStringStream()
    writegoogle_protobuf_Value(ss, message)
    result = ss.data

proc newgoogle_protobuf_Value*(data: string): google_protobuf_Value =
    let
        ss = newStringStream(data)
    result = readgoogle_protobuf_Value(ss)

proc newgoogle_protobuf_Value*(data: seq[byte]): google_protobuf_Value =
    let
        ss = newStringStream(cast[string](data))
    result = readgoogle_protobuf_Value(ss)


proc sizeOfgoogle_protobuf_Struct_FieldsEntryKV(key: string, value: google_protobuf_Value): uint64 =
    result = result + sizeOfTag(1, WireType.LengthDelimited)
    result = result + sizeOfString(key)
    result = result + sizeOfTag(2, WireType.LengthDelimited)
    result = result + sizeOfLengthDelimited(sizeOfgoogle_protobuf_Value(value))

proc writegoogle_protobuf_Struct_FieldsEntryKV(stream: Stream, key: string, value: google_protobuf_Value) =
    protoWriteString(stream, key, 1)
    writeMessage(stream, value, 2)

proc readgoogle_protobuf_Struct_FieldsEntryKV(stream: Stream, tbl: TableRef[string, google_protobuf_Value]) =
    var
        key: string
        gotKey = false
        value: google_protobuf_Value
        gotValue = false
    while not atEnd(stream):
        let
            tag = readTag(stream)
            wireType = wireType(tag)
        case fieldNumber(tag)
        of 1:
            key = protoReadString(stream)
            gotKey = true
        of 2:
            let
                size = readVarint(stream)
                data = safeReadStr(stream, int(size))
                pbs = newStringStream(data)
            value = readgoogle_protobuf_Value(pbs)
            gotValue = true
        else: skipField(stream, wireType)
    if not gotKey:
        raise newException(Exception, "missing key")
    if not gotValue:
        raise newException(Exception, "missing value")
    tbl[key] = value


