# Generated by protoc_gen_nim. Do not edit!

import base64
import intsets
import json
import strutils

import nimpb/nimpb
import nimpb/json as nimpb_json

type
    google_protobuf_Timestamp* = ref google_protobuf_TimestampObj
    google_protobuf_TimestampObj* = object of Message
        seconds: int64
        nanos: int32

proc newgoogle_protobuf_Timestamp*(): google_protobuf_Timestamp
proc newgoogle_protobuf_Timestamp*(data: string): google_protobuf_Timestamp
proc newgoogle_protobuf_Timestamp*(data: seq[byte]): google_protobuf_Timestamp
proc writegoogle_protobuf_Timestamp*(stream: Stream, message: google_protobuf_Timestamp)
proc readgoogle_protobuf_Timestamp*(stream: Stream): google_protobuf_Timestamp
proc sizeOfgoogle_protobuf_Timestamp*(message: google_protobuf_Timestamp): uint64

proc newgoogle_protobuf_Timestamp*(): google_protobuf_Timestamp =
    new(result)
    initMessage(result[])
    result.seconds = 0
    result.nanos = 0

proc clearseconds*(message: google_protobuf_Timestamp) =
    message.seconds = 0
    clearFields(message, [1])

proc hasseconds*(message: google_protobuf_Timestamp): bool =
    result = hasField(message, 1)

proc setseconds*(message: google_protobuf_Timestamp, value: int64) =
    message.seconds = value
    setField(message, 1)

proc seconds*(message: google_protobuf_Timestamp): int64 {.inline.} =
    message.seconds

proc `seconds=`*(message: google_protobuf_Timestamp, value: int64) {.inline.} =
    setseconds(message, value)

proc clearnanos*(message: google_protobuf_Timestamp) =
    message.nanos = 0
    clearFields(message, [2])

proc hasnanos*(message: google_protobuf_Timestamp): bool =
    result = hasField(message, 2)

proc setnanos*(message: google_protobuf_Timestamp, value: int32) =
    message.nanos = value
    setField(message, 2)

proc nanos*(message: google_protobuf_Timestamp): int32 {.inline.} =
    message.nanos

proc `nanos=`*(message: google_protobuf_Timestamp, value: int32) {.inline.} =
    setnanos(message, value)

proc sizeOfgoogle_protobuf_Timestamp*(message: google_protobuf_Timestamp): uint64 =
    if hasseconds(message):
        result = result + sizeOfTag(1, WireType.Varint)
        result = result + sizeOfInt64(message.seconds)
    if hasnanos(message):
        result = result + sizeOfTag(2, WireType.Varint)
        result = result + sizeOfInt32(message.nanos)
    result = result + sizeOfUnknownFields(message)

proc writegoogle_protobuf_Timestamp*(stream: Stream, message: google_protobuf_Timestamp) =
    if hasseconds(message):
        protoWriteInt64(stream, message.seconds, 1)
    if hasnanos(message):
        protoWriteInt32(stream, message.nanos, 2)
    writeUnknownFields(stream, message)

proc readgoogle_protobuf_Timestamp*(stream: Stream): google_protobuf_Timestamp =
    result = newgoogle_protobuf_Timestamp()
    while not atEnd(stream):
        let
            tag = readTag(stream)
            wireType = wireType(tag)
        case fieldNumber(tag)
        of 0:
            raise newException(InvalidFieldNumberError, "Invalid field number: 0")
        of 1:
            expectWireType(wireType, WireType.Varint)
            setseconds(result, protoReadInt64(stream))
        of 2:
            expectWireType(wireType, WireType.Varint)
            setnanos(result, protoReadInt32(stream))
        else: readUnknownField(stream, result, tag)

proc serialize*(message: google_protobuf_Timestamp): string =
    let
        ss = newStringStream()
    writegoogle_protobuf_Timestamp(ss, message)
    result = ss.data

proc newgoogle_protobuf_Timestamp*(data: string): google_protobuf_Timestamp =
    let
        ss = newStringStream(data)
    result = readgoogle_protobuf_Timestamp(ss)

proc newgoogle_protobuf_Timestamp*(data: seq[byte]): google_protobuf_Timestamp =
    let
        ss = newStringStream(cast[string](data))
    result = readgoogle_protobuf_Timestamp(ss)


